/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Paneles.Compartidos;

import Controladores.Buscadores;
import Modelos.Genericos.Solicitud;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author EduardoCGarcia
 */
public class ConsultarStatusPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ConsultarStatusPanel
     */
    public ConsultarStatusPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        FondoHoja = new Utilerias.FondoNoAjustable("TexturaBlanco1.jpeg");
        lblFolio = new javax.swing.JLabel();
        lblFolioSolicitud = new javax.swing.JLabel();
        lblAsunto = new javax.swing.JLabel();
        lblAsuntoSolicitud = new javax.swing.JLabel();
        lblDatosDelSolicitante = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNombreSolicitante = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblNumeroSolicitante = new javax.swing.JLabel();
        lblFechaSolicitud = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        lblEstatusSolicitud = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCorreoSolicitante = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(26, 104, 53));
        setForeground(new java.awt.Color(26, 104, 53));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Folio:");

        txtFolio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        FondoHoja.setBackground(new java.awt.Color(255, 255, 255));

        lblFolio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFolio.setForeground(new java.awt.Color(0, 0, 0));
        lblFolio.setText("Folio");

        lblFolioSolicitud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFolioSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        lblFolioSolicitud.setText("FolioSolicitud");

        lblAsunto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAsunto.setForeground(new java.awt.Color(0, 0, 0));
        lblAsunto.setText("Asunto:");

        lblAsuntoSolicitud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAsuntoSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        lblAsuntoSolicitud.setText("AsuntoSolicitud");

        lblDatosDelSolicitante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDatosDelSolicitante.setForeground(new java.awt.Color(0, 0, 0));
        lblDatosDelSolicitante.setText("Datos del solicitante");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre");

        lblNombreSolicitante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreSolicitante.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreSolicitante.setText("NombreSolicitante");

        lblNumero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblNumero.setText("Numero de cuenta:");

        lblNumeroSolicitante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumeroSolicitante.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroSolicitante.setText("Numero de cuenta Solicitante");

        lblFechaSolicitud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFechaSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaSolicitud.setText("FechaSolicitud");

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha");

        lblEstatus.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEstatus.setForeground(new java.awt.Color(0, 0, 0));
        lblEstatus.setText("Estatus");

        lblEstatusSolicitud.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEstatusSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        lblEstatusSolicitud.setText("EstatusSolicitud");

        lblCorreo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo:");

        lblCorreoSolicitante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorreoSolicitante.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreoSolicitante.setText("CorreoSolicitante");

        javax.swing.GroupLayout FondoHojaLayout = new javax.swing.GroupLayout(FondoHoja);
        FondoHoja.setLayout(FondoHojaLayout);
        FondoHojaLayout.setHorizontalGroup(
            FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoHojaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoHojaLayout.createSequentialGroup()
                        .addComponent(lblFolio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFolioSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaSolicitud)
                        .addGap(41, 41, 41))
                    .addGroup(FondoHojaLayout.createSequentialGroup()
                        .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoHojaLayout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombreSolicitante))
                            .addGroup(FondoHojaLayout.createSequentialGroup()
                                .addComponent(lblCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCorreoSolicitante))
                            .addGroup(FondoHojaLayout.createSequentialGroup()
                                .addComponent(lblNumero)
                                .addGap(18, 18, 18)
                                .addComponent(lblNumeroSolicitante))
                            .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDatosDelSolicitante)
                                .addGroup(FondoHojaLayout.createSequentialGroup()
                                    .addComponent(lblAsunto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblAsuntoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoHojaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoHojaLayout.createSequentialGroup()
                        .addComponent(lblEstatusSolicitud)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoHojaLayout.createSequentialGroup()
                        .addComponent(lblEstatus)
                        .addGap(212, 212, 212))))
        );
        FondoHojaLayout.setVerticalGroup(
            FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoHojaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFolio)
                    .addComponent(lblFolioSolicitud)
                    .addComponent(lblFechaSolicitud)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsunto)
                    .addComponent(lblAsuntoSolicitud))
                .addGap(26, 26, 26)
                .addComponent(lblDatosDelSolicitante)
                .addGap(34, 34, 34)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblNombreSolicitante))
                .addGap(18, 18, 18)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(lblNumeroSolicitante))
                .addGap(18, 18, 18)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(lblCorreoSolicitante))
                .addGap(29, 29, 29)
                .addComponent(lblEstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstatusSolicitud)
                .addGap(46, 46, 46))
        );

        btnBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(FondoHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(FondoHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Solicitud s = Buscadores.findSolicitud(txtFolio.getText());
        if (s != null) {
            lblFolioSolicitud.setText(s.getFolio().getFolio());
            lblFechaSolicitud.setText(s.getFechaDeSolicitud().format(DateTimeFormatter.ISO_LOCAL_DATE));
            lblAsuntoSolicitud.setText(s.getAsunto());
            lblNombreSolicitante.setText(s.getSolitante().getNombre().toString());
            lblCorreoSolicitante.setText(s.getSolitante().getCorreo());
            lblEstatusSolicitud.setText(s.getEstatus());
            lblNumeroSolicitante.setText(s.getSolitante().getNumero());
            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoHoja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblAsuntoSolicitud;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreoSolicitante;
    private javax.swing.JLabel lblDatosDelSolicitante;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblEstatusSolicitud;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaSolicitud;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblFolioSolicitud;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreSolicitante;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroSolicitante;
    private javax.swing.JTextField txtFolio;
    // End of variables declaration//GEN-END:variables
}
