/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Paneles;

/**
 *
 * @author EduardoCGarcia
 */
public class ConsultarStatusPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ConsultarStatusPanel
     */
    public ConsultarStatusPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        FondoHoja = new Utilerias.FondoNoAjustable("TexturaBlanco1.jpeg");
        lblSolicitud = new javax.swing.JLabel();
        lblFolioSolicitud = new javax.swing.JLabel();
        lblAsunto = new javax.swing.JLabel();
        lblAsuntoSolicitud = new javax.swing.JLabel();
        lblDatosDelSolicitante = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNombreSolicitante = new javax.swing.JLabel();
        lblApellidoSolicitante = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblNumeroSolicitante = new javax.swing.JLabel();
        lblSolicitud1 = new javax.swing.JLabel();
        lblSolicitud2 = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        lblEstatusSolicitud = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCorreoSolicitante = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(26, 104, 53));
        setForeground(new java.awt.Color(26, 104, 53));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Folio:");

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        FondoHoja.setBackground(new java.awt.Color(255, 255, 255));

        lblSolicitud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        lblSolicitud.setText("Solicitud:");

        lblFolioSolicitud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFolioSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        lblFolioSolicitud.setText("FolioSolicitud");

        lblAsunto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAsunto.setForeground(new java.awt.Color(0, 0, 0));
        lblAsunto.setText("Asunto:");

        lblAsuntoSolicitud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAsuntoSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        lblAsuntoSolicitud.setText("AsuntoSolicitud");

        lblDatosDelSolicitante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDatosDelSolicitante.setForeground(new java.awt.Color(0, 0, 0));
        lblDatosDelSolicitante.setText("Datos del solicitante");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre");

        lblNombreSolicitante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreSolicitante.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreSolicitante.setText("NombreSolicitante");

        lblApellidoSolicitante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblApellidoSolicitante.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoSolicitante.setText("ApellidoSolicitante");

        lblNumero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblNumero.setText("Numero de cuenta:");

        lblNumeroSolicitante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumeroSolicitante.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroSolicitante.setText("Numero de cuenta Solicitante");

        lblSolicitud1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSolicitud1.setForeground(new java.awt.Color(0, 0, 0));
        lblSolicitud1.setText("FechaSolicitud");

        lblSolicitud2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSolicitud2.setForeground(new java.awt.Color(0, 0, 0));
        lblSolicitud2.setText("FechaSolicitud");

        lblEstatus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEstatus.setForeground(new java.awt.Color(0, 0, 0));
        lblEstatus.setText("Estatus:");

        lblEstatusSolicitud.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEstatusSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        lblEstatusSolicitud.setText("EstatusSolicitud");

        lblCorreo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo:");

        lblCorreoSolicitante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCorreoSolicitante.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreoSolicitante.setText("CorreoSolicitante");

        javax.swing.GroupLayout FondoHojaLayout = new javax.swing.GroupLayout(FondoHoja);
        FondoHoja.setLayout(FondoHojaLayout);
        FondoHojaLayout.setHorizontalGroup(
            FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoHojaLayout.createSequentialGroup()
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoHojaLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(lblDatosDelSolicitante)
                        .addGap(149, 149, 149))
                    .addGroup(FondoHojaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoHojaLayout.createSequentialGroup()
                                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSolicitud)
                                    .addComponent(lblAsunto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFolioSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAsuntoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSolicitud2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSolicitud1))
                            .addGroup(FondoHojaLayout.createSequentialGroup()
                                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FondoHojaLayout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNombreSolicitante)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblApellidoSolicitante))
                                    .addGroup(FondoHojaLayout.createSequentialGroup()
                                        .addComponent(lblCorreo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCorreoSolicitante))
                                    .addGroup(FondoHojaLayout.createSequentialGroup()
                                        .addComponent(lblNumero)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNumeroSolicitante))
                                    .addGroup(FondoHojaLayout.createSequentialGroup()
                                        .addComponent(lblEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(lblEstatusSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(166, 166, 166)))))
                .addGap(46, 46, 46))
        );
        FondoHojaLayout.setVerticalGroup(
            FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoHojaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSolicitud)
                    .addComponent(lblFolioSolicitud)
                    .addComponent(lblSolicitud1)
                    .addComponent(lblSolicitud2))
                .addGap(18, 18, 18)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsunto)
                    .addComponent(lblAsuntoSolicitud))
                .addGap(27, 27, 27)
                .addComponent(lblDatosDelSolicitante)
                .addGap(18, 18, 18)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblNombreSolicitante)
                    .addComponent(lblApellidoSolicitante))
                .addGap(18, 18, 18)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(lblNumeroSolicitante))
                .addGap(18, 18, 18)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(lblCorreoSolicitante))
                .addGap(32, 32, 32)
                .addGroup(FondoHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstatus)
                    .addComponent(lblEstatusSolicitud))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(FondoHoja, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(FondoHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoHoja;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblApellidoSolicitante;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblAsuntoSolicitud;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreoSolicitante;
    private javax.swing.JLabel lblDatosDelSolicitante;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblEstatusSolicitud;
    private javax.swing.JLabel lblFolioSolicitud;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreSolicitante;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroSolicitante;
    private javax.swing.JLabel lblSolicitud;
    private javax.swing.JLabel lblSolicitud1;
    private javax.swing.JLabel lblSolicitud2;
    // End of variables declaration//GEN-END:variables
}
